# Generated by Django 5.0.3 on 2024-03-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
